# fly.toml app configuration file generated for hbnb-backend on 2025-12-20T03:27:46+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hbnb-backend'
primary_region = 'sin'

[build]
  dockerfile = '../../backend/Dockerfile'
  build-target = ''
  context = '../../backend'
  ignorefile = '../../backend/.dockerignore'

[env]
  FLASK_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
